travis:
  secure:
    BINSTAR_TOKEN: OKrmERwniqWE9O1qxZytRQsTutUMiDxRJeBR3Jnz3IPNYuxoDI6YlS48jT+f5zGF5kZCk9TiHQgtBM48KKHKSCUryjvfclW5OXMObw8b92CZhXqzTsYYPKLLWhvZsymLESc01ZUEyY406htgnGcPCd262kykim3KCWA+uC3T++sGCNWSJb8Vwlk1S4QHKfK9ALMTQfnB7b92AZrwFqbE3+2QmOVON7EqcmbMcTJ2vCBwptaGVWJI1mbRebpMYz+jwuwScSOcGmwJOfEY0HtwLv0kjn2UuYAx+GZ+A9TM5kIOEaY55ZJzfYNxIsKinfY/VfC4ezR2Ca8oDqxlzLpe64EQWrOTBhi8kgKpOKnM2Uh/KYYxULzfRGdwGikMI9lkOTvcZ5OwLRisBU+zGiRSVdD3gshvNZ4FIhZ+/5o1ObJnIYBGSgf6TaQrW11Fj0XU9mYQrjGmGNaTAN3mnchZFptY37KUW26/iOEusO0plAyjCV7d4CVCaxNBPnAf2NE4w587Qb43yFHO39myojhHlhMMjhx483Y5V1fTUAw8PP0pakmv1z6n9TJmfn9wFxY8CLmuAGy7mBxXEeQJnLA0baM7GOoa5ZPJfqZwaRW8hM8qkHkPanP/NpN5KUCuUQaP/iLrqdHnZcsjbLnUSkupeujaCIdGxUbfkQzKoKq3vk0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
